// Test semantic error for wrong number of arguments in a function call

func main() returns void {
    int x;
    x = 1;
    int y;
    y = 2;
    test_func(x, y);
}

func test_func(int x) returns void {
    x += 1;
}